name: Profile Metrics & 3D Graph

on:
  schedule:
    - cron: "0 18 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Profile Assets

    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: "drishtiisharma"

          plugin_anilist: yes
          plugin_anilist_user: simplysho
          plugin_anilist_medias: anime, manga, characters
          plugin_anilist_sections: favorites, reading, characters
          plugin_anilist_limit: 5
          plugin_anilist_shuffle: yes

      - name: Commit & Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated 3D graph & AniList cards"
            git pull --rebase origin main
            git push origin main
          fi

