name: Generate AniList Metrics

on:
  schedule:
    - cron: "0 18 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: drishtiisharma
          template: classic
          base: header
          config_timezone: Asia/Kolkata

          plugin_anilist: yes
          plugin_anilist_user: simplysho
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 5
          plugin_anilist_shuffle: yes

          filename: metrics.svg
