name: AniList Metrics

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 11:30 PM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate AniList Stats

    steps:
      - uses: actions/checkout@v4

      - name: Generate AniList Metrics Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Calcutta
          filename: metrics.anilist.svg
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: drishtiisharma
          plugin_anilist_medias: anime, manga, characters
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 5
          plugin_anilist_shuffle: no

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ðŸŽ¬ Updated AniList metrics"
            git pull --rebase origin main
            git push origin main
          fi
